### ISSUE TITLE
Window sizing Problem with Arethusa widget

### ISSUE THREAD

**Issue by TDBuck** [perseids-project/Gardener#1]
Migrating from perseids-project/GardenerPrototype#1 
for some themes (Leap-year and Hacker) the widget loads in too small, but will slowly get bigger if you keep switching between trees.
For most other themes, the window will load, but after switching between trees with "cut" off the bottom of the window.
resizing the window always results in a duplicate of the window appearing below it.

**Comment by balmas** [comment]
closed see perseids-project/GardenerPrototype#1
